# -*- coding: utf-8 -*-
"""Credit Card.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Aaf8FYE9pYcwObw9d6zb1blW2kEXnXiA
"""

!pip install pycaret

from pycaret.datasets import get_data
dataset = get_data('credit')

dataset= dataset[['LIMIT_BAL', 'SEX', 'EDUCATION','MARRIAGE','AGE','default']]

dataset.head()

data = dataset.sample(frac=0.80, random_state=100)
data = data.reset_index(drop=True)
data_unseen = dataset.drop(data.index)
data_unseen= data_unseen.reset_index(drop=True)

from pycaret.classification import *

eda_classification = setup(data = data, target = 'default', session_id=123)

compare_models()

rf = create_model('rf')
tuned_rf = tune_model('rf')

predict_model(tuned_rf)

### Create a Pickle file using serialization 
import pickle
pickle_out = open("CreditCardClassifier.pkl","wb")
pickle.dump(tuned_rf, pickle_out)
pickle_out.close()

import os

os.getcwd()  #show current directory
!pwd  #shows current directory

!ls  #content in current directory


os.chdir(path)   #change directory